databases:
  - name: rudicarrillo
    databaseName: rudicarrillo
    user: rudicarrillo_user

services:
  - type: web
    name: Actions App
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rudicarrillo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false